sudo: false

language: go

go:
  - '1.12.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

before_script:
  - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
  - mkdir -p ~/bin && cd ~/bin && curl -L https://raw.githubusercontent.com/flant/multiwerf/master/get.sh -O && chmod +x get.sh && ./get.sh
  - source <(multiwerf use 1.0 beta)

after_script:
  - go get https://github.com/golang/example
